### ISSUE TITLE
TableUtil.Sync will remove arrays from the original template

### ISSUE THREAD

**Issue by Dog2puppy** [Sleitnick/Knit#14] opened 2020-10-16 00:13 UTC
When using TableUtil.Sync, any empty arrays in the template data will override any arrays in the original template. 

# Reproduction
```lua
local function Sync(tbl, templateTbl) -- this function is coped from the TableUtil file

    assert(type(tbl) == "table", "First argument must be a table")
    assert(type(templateTbl) == "table", "Second argument must be a table")
    
    -- If 'tbl' has something 'templateTbl' doesn't, then remove it from 'tbl'
    -- If 'tbl' has something of a different type than 'templateTbl', copy from 'templateTbl'
    -- If 'templateTbl' has something 'tbl' doesn't, then add it to 'tbl'
    for k,v in pairs(tbl) do
        
        local vTemplate = templateTbl[k]
        
        -- Remove keys not within template:
        if (vTemplate == nil) then
            tbl[k] = nil
            
        -- Synchronize data types:
        elseif (type(v) ~= type(vTemplate)) then
            if (type(vTemplate) == "table") then
                tbl[k] = CopyTable(vTemplate)
            else
                tbl[k] = vTemplate
            end
        
        -- Synchronize sub-tables:
        elseif (type(v) == "table") then
            Sync(v, vTemplate)
        end
        
    end
    
    -- Add any missing keys:
    for k,vTemplate in pairs(templateTbl) do
        
        local v = tbl[k]
        
        if (v == nil) then
            if (type(vTemplate) == "table") then
                tbl[k] = CopyTable(vTemplate)
            else
                tbl[k] = vTemplate
            end
        end
        
    end
    
end

local t1 = { Stamps = {"Level-1"} }
local t2 = { Stamps = {} }
print(t1) -- notice how t1 has Level-1 in it here
Sync(t1, t2)
print(t1) -- and it now no longer has Level-1
```

**Comment by OverHash** [comment] 2020-10-16 00:22
This is intended behavior - from the docs "If the table has something that the template does not have, it gets removed."

**Comment by Dog2puppy** [comment] 2020-10-16 02:27
Any workarounds if this is apparently intended?

**Comment by Sleitnick** [comment] 2020-11-13 15:50
@Dog2puppy Are you maybe just trying to do an 'extend'? Essentially you just append one table to the end of another (Which is something I want to add to this library.) If you want a shallow copy version for arrays, this can be done with `table.move`:

```lua
-- Add 't2' to the end of 't1':
local function Extend(t1, t2)
    table.move(t2, 1, #t2, #t1 + 1, t1)
end
```

For a deep copy, or for key-pair dictionaries, you'd just have to a recursive scan and basically do a one-way sync.

**Comment by Sleitnick** [comment] 2021-01-11 22:19
Closing this for now

**Closed by Sleitnick** 2021-01-11 22:19 UTC
